// Frontend build: esbuild for the JavaScript, Tailwind CLI for the stylesheet,
// plus a plain copy of index.html and the logo assets into dist/.
//
// Deliberately small — no bundler config to maintain, and `node build.mjs`
// produces exactly what Tauri ships.

import * as esbuild from 'esbuild';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import { fileURLToPath } from 'node:url';

const run = promisify(execFile);

// fileURLToPath, not `new URL(...).pathname`. On Windows the latter yields
// "/D:/JWS%20Attendance%20System/..." — a leading slash and percent-encoded
// spaces — which path.join then turns into "D:\D:\JWS%20Attendance...".
const root = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(root, 'src');
const OUT = path.join(root, 'dist');

const watch = process.argv.includes('--watch');
const serve = process.argv.includes('--serve');
const dev = watch || serve;


/**
 * Extract the Bikram Sambat month-length table out of the Rust source.
 *
 * The demo backend and the browser test suite need the same table the app
 * uses, and hand-copying ninety-one rows of month lengths into JavaScript is
 * exactly the sort of thing that goes wrong once and then quietly reports the
 * wrong Nepali date for a year. Generating it means there is still only one
 * copy anyone edits.
 */
async function generateBsTable() {
  const rs = await fs.readFile(
    path.join(root, 'crates', 'zk-core', 'src', 'calendar.rs'), 'utf8');

  const block = /static BS_MONTHS:\s*\[\[u8;\s*12\];\s*\d+\]\s*=\s*\[([\s\S]*?)\n\];/
    .exec(rs);
  if (!block) throw new Error('could not find BS_MONTHS in calendar.rs');

  const months = [...block[1].matchAll(/\[([0-9,\s]+)\]/g)]
    .map((m) => m[1].split(',').map((n) => Number(n.trim())).filter((n) => n));

  const startYear = Number(/const BS_START_YEAR: i32 = (\d+)/.exec(rs)?.[1]);
  const endYear = Number(/const BS_END_YEAR: i32 = (\d+)/.exec(rs)?.[1]);
  const anchor = /const ANCHOR_AD: \(i32, u32, u32\) = \((\d+),\s*(\d+),\s*(\d+)\)/.exec(rs);

  if (!startYear || !endYear || !anchor) throw new Error('calendar.rs constants not found');
  if (months.length !== endYear - startYear + 1) {
    throw new Error(`extracted ${months.length} years, expected ${endYear - startYear + 1}`);
  }
  for (const [i, row] of months.entries()) {
    if (row.length !== 12) throw new Error(`year ${startYear + i} has ${row.length} months`);
  }

  const table = {
    min_year: startYear,
    max_year: endYear,
    months,
    month_names: ['Baisakh', 'Jestha', 'Ashadh', 'Shrawan', 'Bhadra', 'Ashwin',
      'Kartik', 'Mangsir', 'Poush', 'Magh', 'Falgun', 'Chaitra'],
    digits: ['०', '१', '२', '३', '४', '५', '६', '७', '८', '९'],
    day_names: ['Aaitabar', 'Sombar', 'Mangalbar', 'Budhabar', 'Bihibar', 'Sukrabar', 'Sanibar'],
    day_names_short: ['Aai', 'Som', 'Man', 'Bud', 'Bihi', 'Suk', 'Sani'],
    anchor_ad: `${anchor[1]}-${String(anchor[2]).padStart(2, '0')}-${String(anchor[3]).padStart(2, '0')}`,
  };

  await fs.writeFile(
    path.join(SRC, 'js', 'bs-table.generated.js'),
    `// GENERATED by build.mjs from crates/zk-core/src/calendar.rs — do not edit.\n`
    + `// Used by the demo backend so the browser build has the same Nepali\n`
    + `// calendar the app does. Edit the Rust table, then rebuild.\n`
    + `export const BS_TABLE = ${JSON.stringify(table)};\n`,
    'utf8',
  );
}

async function copyStatic() {
  await fs.mkdir(path.join(OUT, 'assets'), { recursive: true });
  await fs.copyFile(path.join(SRC, 'index.html'), path.join(OUT, 'index.html'));
  for (const f of await fs.readdir(path.join(SRC, 'assets'))) {
    await fs.copyFile(path.join(SRC, 'assets', f), path.join(OUT, 'assets', f));
  }
}

async function buildCss() {
  // Invoke Tailwind's JS entry point through node rather than the wrapper in
  // node_modules/.bin. On Windows that wrapper is a .cmd, which recent Node
  // refuses to spawn without a shell; on Linux it is an extensionless script.
  // Going straight to cli.js sidesteps both.
  const cli = path.join(root, 'node_modules', 'tailwindcss', 'lib', 'cli.js');
  const args = [cli, '-i', path.join(SRC, 'styles.css'), '-o', path.join(OUT, 'app.css')];
  if (!dev) args.push('--minify');
  try {
    await run(process.execPath, args);
  } catch (e) {
    // Tailwind writes its progress banner to stderr, so only a non-zero exit
    // with no output file is a real failure.
    try {
      await fs.access(path.join(OUT, 'app.css'));
    } catch {
      throw new Error(`Tailwind build failed:\n${e.stderr || e.message}`);
    }
  }
}

const jsOptions = {
  entryPoints: [path.join(SRC, 'js', 'main.js')],
  bundle: true,
  format: 'iife',
  target: ['chrome110'],
  outfile: path.join(OUT, 'app.js'),
  sourcemap: dev,
  minify: !dev,
  logLevel: 'info',
  legalComments: 'none',
};

await generateBsTable();
await fs.rm(OUT, { recursive: true, force: true });
await copyStatic();
await buildCss();

if (watch) {
  const ctx = await esbuild.context(jsOptions);
  await ctx.watch();

  // Tailwind and the static files do not have a watcher of their own; polling
  // the source directory is plenty for a project this size.
  let last = 0;
  setInterval(async () => {
    const stat = await fs.stat(path.join(SRC, 'styles.css')).catch(() => null);
    const html = await fs.stat(path.join(SRC, 'index.html')).catch(() => null);
    const newest = Math.max(stat?.mtimeMs ?? 0, html?.mtimeMs ?? 0);
    if (newest > last) {
      last = newest;
      await copyStatic();
      await buildCss();
    }
  }, 700);

  if (serve) {
    const port = 5173;
    const types = {
      '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css',
      '.png': 'image/png', '.svg': 'image/svg+xml', '.map': 'application/json',
    };
    http
      .createServer(async (req, res) => {
        const url = decodeURIComponent((req.url || '/').split('?')[0]);
        const file = path.join(OUT, url === '/' ? 'index.html' : url);
        try {
          const body = await fs.readFile(file);
          res.writeHead(200, { 'Content-Type': types[path.extname(file)] || 'application/octet-stream' });
          res.end(body);
        } catch {
          // Single-page app: unknown paths fall back to the shell.
          const body = await fs.readFile(path.join(OUT, 'index.html'));
          res.writeHead(200, { 'Content-Type': 'text/html' });
          res.end(body);
        }
      })
      .listen(port, () => console.log(`dev server on http://localhost:${port}`));
  }
} else {
  await esbuild.build(jsOptions);
  console.log('frontend built to dist/');
}
